

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend_${APP_NAME}
    working_dir: /var/www
    volumes:
      - ./src:/var/www        
      - ./src/vendor:/var/www/vendor 
    networks:
      - internal
    depends_on:
      - db
    user: "${UID}:${GID}"   

  web:
    image: nginx:alpine
    container_name: web_laravel
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public
      - internal
    depends_on:
      - backend
  cache:
    image: redis:latest
    container_name: laravel_cache
    networks:
      - internal
  email:
    image: mailhog/mailhog:v1.0.1
    container_name: laravel_mail
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - internal
      - public
  db:
    image: postgres:16-alpine
    container_name: laravel_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
      - public
      - internal

networks:
  public:
  internal:
    internal: true

volumes:
  db_data:


x-args:
  UID: ${UID:-1000}
  GID: ${GID:-1000}
